### ISSUE TITLE
Error when using the production command "ionic cordova run browser —prod"

### ISSUE THREAD

**Issue by msangalli** [cometchat-pro/javascript-chat-sdk#1]
After compiling (ionic-app-scripts 3.2.2 + Angular 4.4.3) with production command "ionic cordova run browser —prod”,  when I try to login the user the error[ “Cannot set property ‘endpoint’ of undefined”](
https://drive.google.com/open?id=1JetpDdFafozqDrxYEKO9QKt0rCvAF7IN) is raised.

`vendor.js:1 ERROR Error: Uncaught (in promise): TypeError: Cannot set property 'endpoint' of undefined
TypeError: Cannot set property 'endpoint' of undefined
    at vendor.js:1
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (vendor.js:1)
    at t.invoke (polyfills.js:3)
    at r.run (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (vendor.js:1)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at c (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (vendor.js:1)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at o (polyfills.js:3)
    at e.invokeTask [as invoke] (polyfills.js:3)
    at p (polyfills.js:2)
    at XMLHttpRequest.v (polyfills.js:2)`

[The code](https://drive.google.com/open?id=17OA-6OiP0oosMgtRaIOv0Qr3HGhWOP9V):

```
return t.prototype.getEndpointData = function(t) {
                    var e = this;
                    return new Promise(function(n, s) {
                        o.LocalStorage.getInstance().get(i.APP_SETTINGS.APP_SETTINGS).then(function(o) {
                            if (r.isFalsy(o)) {
                                var s = void 0;
                                e.uriEndpoints.hasOwnProperty(t) && (s.endpoint = (s = e.uriEndpoints[t]).hasOwnProperty(["isAdminApi"]) ? e.adminApiUrl + e.adminApiVersion + "/" + s.endpoint : e.baseUrl + e.apiVersion + "/" + s.endpoint),
                                n(s)
                            } else
                                s = void 0,
                                e.uriEndpoints.hasOwnProperty(t) && (s.endpoint = (s = e.uriEndpoints[t]).hasOwnProperty(["isAdminApi"]) ? "https://" + o[i.APP_SETTINGS.KEYS.ADMIN_API_HOST] + "/" + e.adminApiVersion + "/" + s.endpoint : "https://" + o[i.APP_SETTINGS.KEYS.CLIENT_API_HOST] + "/" + e.apiVersion + "/" + s.endpoint),
                                n(s)
                        }, function(r) {
                            var i;
                            e.uriEndpoints.hasOwnProperty(t) && (i.endpoint = (i = e.uriEndpoints[t]).hasOwnProperty(["isAdminApi"]) ? e.adminApiUrl + e.adminApiVersion + "/" + i.endpoint : e.baseUrl + e.apiVersion + "/" + i.endpoint),
                            n(i)
                        })
                    }
                    )
                }
```

The error is generated inside the first else:

`e.uriEndpoints.hasOwnProperty(t) && (s.endpoint = (s = e.uriEndpoints[t]).hasOwnProperty(["isAdminApi"]) ? "https://" + o[i.APP_SETTINGS.KEYS.ADMIN_API_HOST] + "/" + e.adminApiVersion + "/" + s.endpoint : "https://" + o[i.APP_SETTINGS.KEYS.CLIENT_API_HOST] + "/" + e.apiVersion + "/" + s.endpoint),
                                n(s)`

It seem it can’t write to local storage. In fact [checking the local storage](https://drive.google.com/open?id=15KivNXIh8-s4RpvIvLwmmPnkGYQ0muo3) there isn’t the app_settings.

In dev mode, compiling with "ionic serve" or "ionic cordova run browser" the code works without problems and the [app_settings is correctly created in the local storage](https://drive.google.com/open?id=1RuGOIq-d_Ft6SeYSDGEyoMH9NwbHllk5).

Thank you, m.

**Comment by ajaygajra** [comment]
@msangalli , hey we are looking in to it.
we will update it as soon as possible.

**Comment by msangalli** [comment]
> @msangalli , hey we are looking in to it.
> we will update it as soon as possible.

Thank you @ajaygajra, let me know if you need other info.

**Comment by ajaygajra** [comment]
@msangalli, currently we are working on issue, and soon going to release the new build, so you can compile your production build, thanks for bear with us.

**Comment by msangalli** [comment]
> @msangalli, currently we are working on issue, and soon going to release the new build, so you can compile your production build, thanks for bear with us.

@ajaygajra, amazing! Thank you

**Comment by msangalli** [comment]
hi @ajaygajra did you have news about this?

**Comment by ajaygajra** [comment]
Hi @msangalli we have released the new version 1.4.0. Please update the SDK.

**Comment by msangalli** [comment]
@ajaygajra I'm testing the 1.4:

### WITH '-prod' flag:

Now is able to write the app_settings:

![Screenshot 2019-05-02 at 10 07 36](https://user-images.githubusercontent.com/17550201/57062974-22835b80-6cc2-11e9-802b-2dafb78a5ca9.png)

It's able to listen new messages:

```
  listenForMessages(listenerId: string, onMessageReceived: (msg: any) => void) {
    CometChat.addMessageListener(
      listenerId,
      new CometChat.MessageListener({
        onTextMessageReceived: onMessageReceived,
        onMediaMessageReceived: _ => undefined
      })
    );
  }
```
Output:
![Screenshot 2019-05-02 at 10 08 45](https://user-images.githubusercontent.com/17550201/57063030-4c3c8280-6cc2-11e9-8b7c-262919c220f6.png)

But when I call:

```
    const messageRequest = new CometChat.MessagesRequestBuilder()
      .setGUID(groupId)
      .setLimit(100)
      .build();

    return messageRequest.fetchPrevious();
```

![Screenshot 2019-05-02 at 10 11 23](https://user-images.githubusercontent.com/17550201/57063178-aa696580-6cc2-11e9-860c-209c4eb2ad39.png)

![Screenshot 2019-05-02 at 10 13 14](https://user-images.githubusercontent.com/17550201/57063269-f7e5d280-6cc2-11e9-9042-d5092bdf6cfe.png)

`
 t="getGroupMessages"
 e.apiVersion = "v1.3"
`

### WITHOUT '-prod' flag: ionic serve

Now, when I call the login method:

![Screenshot 2019-05-02 at 10 21 12](https://user-images.githubusercontent.com/17550201/57063586-084a7d00-6cc4-11e9-9e21-d87430daf6f1.png)

![Screenshot 2019-05-02 at 10 25 58](https://user-images.githubusercontent.com/17550201/57063791-b48c6380-6cc4-11e9-997f-0e46a0a62ae1.png)

I hope this can help.

**Comment by ajaygajra** [comment]
@msangalli can you try a clean install once (cleaning the local storage once)
