### ISSUE TITLE
Video conference issue

### ISSUE THREAD

**Issue by anantgarg** [cometchat-pro/javascript-chat-sdk#16]
Made a group video call from user "X". After I left the account, again tried to go, but for some reason no reaction after that was not followed.
The console displays an error.
Through other user tried to enter, everything is good, but each time when I cancel the notification of a video call from the user "X" and again I am authorized, again climbs out the notification from the user "X".
And this happens with every user. But log in to the user "X" is not possible. Is the latest version from Github.

![image](https://user-images.githubusercontent.com/168350/60045385-ff51a880-9681-11e9-809b-2340aa4532ef.png)

**Comment by mayur-bhandari** [comment]
@anantgarg , can you please elaborate on this and can you please update Js SDK to the latest version i.e 1.8.12 and try the same scenario.
