### ISSUE TITLE
How can I get only the unread user's messages from the groups he joined?

### ISSUE THREAD

**Issue by msangalli** [cometchat-pro/javascript-chat-sdk#2]
I'm trying to create some kind of visual notification alerting the user when is back online and I need to know if there are unread new messages for the user in the groups he joined.

How can I accomplish that?

When I use the listener 'onMessageDelivered' on a group, at the start it returns also the old messages that I marked with markMessageAsRead:

```
CometChat.addMessageListener("listenerId", new CometChat.MessageListener({
  onMessageDelivered: (messageReceipt) => {
    console.log("MessageDeliverd", {messageReceipt});
  },onMessageRead: (messageReceipt) => {
    console.log("MessageRead", {messageReceipt});
  }
}));
```

![Screenshot 2019-04-16 at 20 49 04](https://user-images.githubusercontent.com/17550201/56236156-3b1c3080-6089-11e9-9b8e-3a5d77d6a2ad.png)

How does it work 'markMessageAsRead' for a group message?

CometChat.markMessageAsRead(message);

Is it correct if I ask these kind of questions here?

Thank you, m.

**Comment by kshitizshakya-cc** [comment]
Hello @msangalli, 

We like to inform you that we are working on the same. We will connect you with the appropriate solution as soon as possible. 

Also adding to that you can also connect our community slack channel 

Link: https://slack.cometchat.com/ 

Warm regards,
Kshitiz

**Comment by msangalli** [comment]
Thank you @kshitizshakya! I joined the slack workspace. Do you have any kind of public roadmap? Your comet chat pro service is great and it could be useful to know about little bit about your planning.

**Comment by ranjanravi85** [comment]
@msangalli Currently we don't have as such public roadmap, however we do have feature request tool  where one can request for feature and the same can be voted by other developers and accordingly we take that specific feature on priority.
