### ISSUE TITLE
Issue with GroupRequestBuilder,  setSearchKeyWord is not a function  

### ISSUE THREAD

**Issue by kshitizshakya-cc** [cometchat-pro/javascript-chat-sdk#23]
Error received  : 

![Screenshot 2019-07-25 at 6 06 56 AM](https://user-images.githubusercontent.com/8190746/61837443-71e0be80-aea2-11e9-9b23-8adffd215f47.png)

Code : 
let groupsRequest = new CometChat.GroupsRequestBuilder().setLimit(100).setSearchKeyWord(key).build();

**Comment by mayur-bhandari** [comment]
Hello @kshitizshakya, this issue has been fixed in the latest javascript sdk (v1.8.7)
