### ISSUE TITLE
Call listners not working - javascript

### ISSUE THREAD

**Issue by ghost** [cometchat-pro/javascript-chat-sdk#25]
<img width="731" alt="calllistner-compile error" src="https://user-images.githubusercontent.com/14342556/62195828-6c034580-b39a-11e9-9dd8-8cbe506a44f4.png">
Initially the call-listener function throws an error saying it would accept only string as its parameter and after removing the  "cometchat.d.ts" file from the node modules, I see that none of the 
incoming listeners are working.

eg: when I make a call from my web app, the call works and rings, but if the attender attends it there is no response in the call listener. Also I do not get any incoming call as well. 

You may also test other cases to make sure its working.

NOTE: am developing the web app in angular6+

**Comment by mayur-bhandari** [comment]
Hello @abilasharjunan, 

We checked our app and it is working as expected. 
The code snippet you shared is insufficient to provide any support for your query. I request you to please share the full code block of addCallListener() implementation.

Also, Please follow the following link to know more about how to implement addCallListener().
link: https://prodocs.cometchat.com/docs/js-calling#section-receive-calls

**Comment by mayur-bhandari** [comment]
Closed due to inactivity.
