### ISSUE TITLE
UserRequestBuilder fetches all users even after using setStatus(CometChat.USER_STATUS.ONLINE)

### ISSUE THREAD

**Issue by mayur-bhandari** [cometchat-pro/javascript-chat-sdk#28]
The UsersRequestBuilder fetches all the users even if setStatus is set to online.

**Comment by VisiBoost** [comment]
Hi Cometchat team,

Any update about this issue ? 
I can't keep hundreds of users in my Online Users List when only 10 are really logged ...

Can you give me a fix even if it is not merged into lasts realases ?

**Comment by mayur-bhandari** [comment]
Hi @VisiBoost , we have fixed this issue, please use our latest sdk v1.8.7
