### ISSUE TITLE
BlockedUsersRequestBuilder not found 

### ISSUE THREAD

**Issue by Mughees605** [cometchat-pro/javascript-chat-sdk#29]
Getting an issue when running sample ionic app with latest comechat sdk

**Comment by mayur-bhandari** [comment]
Hello @Mughees605 , please create an issue on ionic sample app. And please provide a code snippet, it would help us to resolve your issue.

**Comment by mayur-bhandari** [comment]
Hello @Mughees605 , i have created an issue on ionic sample app github repository.
You can track the issue here: https://github.com/cometchat-pro-samples/ionic-chat-app/issues/3
