### ISSUE TITLE
[1.8.8] Inconsistency in naming for action message for Scope changed

### ISSUE THREAD

**Issue by pushpsenairekar2911** [cometchat-pro/javascript-chat-sdk#35]
*Describe the bug**
On Android, we get "System made Joe Doe admin" text
On iOS, we get "Joe Doe's scope changed from participant to participant" text

**Expected behavior**
Action message should be the same. 

**Actual behavior**
getting different action message for the same action.

**Comment by mayur-bhandari** [comment]
Solved it in v1.8.9
