### ISSUE TITLE
Call end is not working on click call end(red round) button in calling GUI.

### ISSUE THREAD

**Issue by Ketan-Infyom** [cometchat-pro/javascript-chat-sdk#37]
- I've integrated audio/video Calling using  Comet Chat v2.0.0-beta5 in vuejs application. every thing is working fine but call end not working on click call end(red round) button in calling GUI.

- **Screenshots:**
![chat-2](https://user-images.githubusercontent.com/28335145/65854141-64035a00-e379-11e9-8f0f-ba5d8afd9b43.PNG)
![chat-3](https://user-images.githubusercontent.com/28335145/65854143-65348700-e379-11e9-99d1-72a606a7007f.PNG)

And one more thing.
- While call connected also get a console error like ↓
![chat-1](https://user-images.githubusercontent.com/28335145/65854177-82695580-e379-11e9-81f0-f7a1db356724.PNG)

**Comment by minisemi** [comment]
I just ran into the same problem on the latest version of Chrome (it works on Firefox) with group calls for v2.0.0-beta4. When I try to end the call using Comet Chat's red end call button in their call window UI in Chrome, I get the following error which results in the call window UI never disappearing.

![image (2)](https://user-images.githubusercontent.com/4705200/66431244-ed6ef800-ea1b-11e9-9694-f69c258f5014.png)

**Comment by mayur-bhandari** [comment]
Hello @Ketan-Infyom, we have solved this in our latest release. Can you  please update to latest version and let us know if it works as intended.

**Comment by mayur-bhandari** [comment]
Closed due to inactivity. Please check the latest version of beta and re open the issue if the error still exist.
