### ISSUE TITLE
Error while sending Media Message

### ISSUE THREAD

**Issue by kshitizshakya-cc** [cometchat-pro/javascript-chat-sdk#4]
There is issue with respect to Media message, 

Cannot send media message. 

SDK version : 1.3.0

Error received : {"code":"ERR_BAD_REQUEST","message":"Failed to validate the data sent with the request.","details":{"data":["The data field is required."]}}

**Comment by ajaygajra** [comment]
@kshitizshakya can you please confirm if the issue is resolved :D
