### ISSUE TITLE
Leave Group - user leaving the group is not notified via GroupListener

### ISSUE THREAD

**Issue by rshubbard** [cometchat-pro/javascript-chat-sdk#44]
When a user leaves the group via https://prodocs.cometchat.com/v2.0/reference#user-leavegroup, they do not receive the action via CometChat.GroupListener.  Other users see the action message via onGroupMemberLeft but not the user who is leaving the group.  If the user does a subsequent call to fetchPrevious() they do see the action message { action: "left" } but there is currently no active listener event to notify that the user has left the group.

I would expect the user leaving the group to also receive a onGroupMemberLeft via the CometChat.GroupListener to let them know they have been removed from the group.

**Comment by ketanyekale** [comment]
Thank you for reporting this issue. The fix will be made live early next week.

**Comment by rshubbard** [comment]
This is still broken on my end.  When a user is removed from a group they
are not receiving the GroupListener callback.

*Robert Hubbard*
*CTO*
Mobile: 919-606-0799
*REVERBNATION*
why we rock <https://www.youtube.com/watch?v=MHPz0zUNPPc>

**Comment by mayur-bhandari** [comment]
Hello @rshubbard , we have released a new SDK v2.0.0-beta10 and have fixed this issue. Can you please check it on your end and let us know if this issue is resolved?

**Comment by mayur-bhandari** [comment]
This issue has been fixed in v2.0.0-beta10. If the issue still persist, please feel free to re open the issue.
