### ISSUE TITLE
Blocked a frame with origin "https://caesar.cometchat.com" from accessing a cross-origin frame.

### ISSUE THREAD

**Issue by caglarturkurka** [cometchat-pro/javascript-chat-sdk#48]
I reviewed https://www.cometchat.com/tutorials/angular-voice-video-chat/ this example project and I upgraded comet-chat-pro version to 1.8.13 and same problem is occurred in here. First time, end button works fine but If you try it more than one, browser gives this error => [JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>: UnhandledError: null Script: null Line: null Column: null StackTrace: Error: Strophe: User connection callback caused an exception: SecurityError: Blocked a frame with origin "https://caesar.cometchat.com" from accessing a cross-origin frame.

**Comment by mayur-bhandari** [comment]
Hello @caglarturkurka , we have released new SDK version 2.0.0-beta9. Can you please check and let us know if this issue is solved in the latest release?
