### ISSUE TITLE
 Module not found: Can't resolve 'react-native'

### ISSUE THREAD

**Issue by mihailgaberov** [cometchat-pro/javascript-chat-sdk#5]
I am getting a warning when run a react app with cometchat dependency:
Compiled with warnings.

./node_modules/@cometchat-pro/chat/CometChat.js
Module not found: Can't resolve 'react-native' in 'C:\...\node_modules\@cometchat-pro\chat'

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

**Comment by kshitizshakya-cc** [comment]
Hello @mihailgaberov , 

We like to inform you that reported issue is warning received when you are not using react-native library in your javascript project. We can assure you that this issue will not affect your app development process. Also, We will remove this warning in the upcoming SDK release.
