### ISSUE TITLE
How do i mark multiple messages as read?

### ISSUE THREAD

**Issue by mike-van** [cometchat-pro/javascript-chat-sdk#51]

**Comment by anantgarg** [comment]
In v2, our markAsRead method will automatically mark all previous messages as read.

**Comment by mike-van** [comment]
great, but im using 1.8 cos in v2 doesnt support my region.

**Comment by mike-van** [comment]
is there anyway to do that in v1.8

**Comment by anantgarg** [comment]
@Mike-Van CometChat Pro v1 has only a single region- EU. CometChat Pro v2 has two region support- EU & US. So you can upgrade to v2 and use EU as the region if you like. You simply need to select a region closest to you; it does not mean that your region is not supported.

We only have this feature in v2.
