### ISSUE TITLE
Error: Failed to execute 'send' on 'websocket' : Still in CONNECTING state.

### ISSUE THREAD

**Issue by torresjeremyrenzo** [cometchat-pro/javascript-chat-sdk#53]
![image](https://user-images.githubusercontent.com/57520064/68456893-f1b84c00-0239-11ea-9539-51556858bb1e.png)

I'm receiving this error message continuously upon going to my site's messages page. But upon reloading the error message doesn't occur anymore. This is happening on the first time that my messages page is loaded. Right after the user has logged in. I'm on CometChat pro v2.0.0-beta10.

**Comment by diegomura** [comment]
@torresjeremyrenzo experiencing the same thing. How did you fix it?

**Comment by karthic-kailanware** [comment]
@torresjeremyrenzo I am also facing the same issue, How did you fix it?

**Comment by meesrutten** [comment]
I am receiving this issue as well. I am using the React Example from the prodocs.
Is there a fix or more documentation about this?

**Comment by mohammedmulazada** [comment]
Same issue.

**Comment by mayur-bhandari** [comment]
I am reopening this issue as it is still relevant to some other users. 

Can you please provide exact steps to reproduce the issue. Also can you please let us know which version of the SDK are you using. Also, if you are using any of our sample apps, please provide the link of the sample app in which you are getting this error.

**Comment by mayur-bhandari** [comment]
This issue occurs if the client is not connected to the Web Sockets and tries to use real-time functions like marking messages as read, sending typing indicators, etc. We have added a new Listener to listen for the status of the connection of the Web Sockets. Please refer to the documentation here: https://prodocs.cometchat.com/docs/js-advanced-connection-listeners
