### ISSUE TITLE
Missing TypeScript definitions on ^1.8.13

### ISSUE THREAD

**Issue by lourensdev** [cometchat-pro/javascript-chat-sdk#56]
I'm having to implement v1.8 into my project and found that there is no TypeScript definition for 
`deleteMessage`

Haven't checked for more but would this still be resolved now that v2 is out?
Workaround was to just type cast it
`(CometChat as any).deleteMessage(...`

**Comment by mayur-bhandari** [comment]
Hello @lourensdev , thanks for reporting the issue. We are working on the type definitions support. We will let you know when it gets live.

**Comment by mayur-bhandari** [comment]
Hello @lourensdev , we have made changes regarding the typescript definitions in our latest release v1.8.15
