### ISSUE TITLE
gettype error

### ISSUE THREAD

**Issue by soganideepak** [cometchat-pro/javascript-chat-sdk#59]
Hi 
getting this error when tyring to make a video call. 
Running version : "@cometchat-pro/chat": "^1.8.3"

ERROR TypeError: Cannot read property 'getType' of undefined
    at o.startCall (CometChat.js:1)
    at Function.a.startCall (CometChat.js:1)
    at SafeSubscriber._next (cometchat.service.ts:28)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:253)
    at SafeSubscriber.next (Subscriber.js:191)
    at Subscriber._next (Subscriber.js:129)
    at Subscriber.next (Subscriber.js:93)
    at FilterSubscriber._next (filter.js:85)
    at FilterSubscriber.Subscriber.next (Subscriber.js:93)
    at ReplaySubject.Subject.next (Subject.js:53)

Let us know how i can resolve that issue.

**Comment by mayur-bhandari** [comment]
Hello @soganideepak , can you please update the cometchat package to 1.8.15 and let us know if your issue still persist.

**Comment by soganideepak** [comment]
Hi 
Thanks for providing the response. One more issue I am facing on the mobile some devices do not showing the video on the full screen.  only showing small my and opposite user in small window remaining screen is showing the image of the play button. 
See the screen shot.
![a1c8c3c9-d642-4ba2-b5a4-0a462c4fa211](https://user-images.githubusercontent.com/11259176/70077376-b8031700-1626-11ea-937c-019f4f3b42f3.jpg)

Thanks

**Comment by mayur-bhandari** [comment]
Hello @soganideepak ,

I would suggest you use our latest SDK v2.x. We have added a few new features and some important fixes.
1. We have added region-based deployment for the apps. This means that you can now select where your apps are hosted. Currently, we have two regions available (EU and US).
2. We have revamped our read receipts functionality. Starting v2, you will just have to mark the last message as read and all the above messages for that particular conversation will be marked as read.
3. We have added options for User presence subscription which include the below options :
- presence of all users
- presence of only friends
- presence of users belonging to specific roles
4. We have added a few more options to fetch Users, Groups, and messages based on different parameters
5. We have added a bunch of extensions to enhance the chat functionality
6. We have added modified our calling component to add more stability

You can log in to https://app.cometchat.io and log in with your account and create a region-based app for the same.

Also, you will have to use the 2.x versions of the SDKs for the v2 apps as SDK versions 1.8.x will not be compatible with the same.

Please let us know if you need any help with the migration. You can find the migration guide [here](https://prodocs.cometchat.com/docs/js-resources-upgrading-from-v1).

Our new calling component is in beta, please use v2.1.0-beta1
