### ISSUE TITLE
Not able to initialize the App

### ISSUE THREAD

**Issue by dushyantRathore** [cometchat-pro/javascript-chat-sdk#6]
I have the folder directory similar to the image shown below :
![Capture](https://user-images.githubusercontent.com/17358196/57684757-0c778280-7654-11e9-9fea-51adcfe56218.JPG)

I have installed the node module using npm. 

Now, when I try to run the following code block by importing the module in html code the file test.html, I don't see anything in the console output. 

```
<html>
<head>
</head>
<body>
<script type="text/html">
import { CometChat } from "./node_modules/@cometchat-pro/chat";
var appID = "MY_APP_ID";
CometChat.init(appID).then(
  hasInitialized => {
    console.log("Initialization completed successfully", hasInitialized);
    // You can now call login function.
  },
  error => {
    console.log("Initialization failed with error:", error);
    // Check the reason for error and take apppropriate action.
  }
);
</script>

</body>
</html>
```

If possible, can you redirect me to a working javascript code for the same..since it lacks in the documentation/Github repo as well

**Comment by ajaygajra** [comment]
Hello @dushyantRathore 
If you wish to use it with javascript browser environment, you can include the script in following way
<script type="text/javascript" src="https://unpkg.com/@cometchat-pro/chat@1.4.1/CometChat.js"></script>

**Comment by dushyantRathore** [comment]
Got it working..thanks.

**Comment by ranjanravi85** [comment]
Hello @dushyantRathore closing the issue since it has been resolved..
