### ISSUE TITLE
End call programmatically?

### ISSUE THREAD

**Issue by bojan-radicevic** [cometchat-pro/javascript-chat-sdk#62]
Is there a way to programmatically end call in Cometchat using JavaScript?

I have a situation where when a game with a friend ends in my app user gets redirected to another page, and if a user tries to play another game with the same friend he can not establish a call because of next error:

![Screenshot from 2020-02-11 12-22-09](https://user-images.githubusercontent.com/44140174/74232624-78f9dd80-4cc9-11ea-9267-ace5d841aafc.png)

Using "@cometchat-pro/chat": "2.0.5"

**Comment by mayur-bhandari** [comment]
Hello @bojan-radicevic, 

We have added a method in the latest version of the JS SDK (v2.0.6) to end call programmatically by calling the end call method:

```
CometChat.endCall(sessionId).then(
    call => {
        console.log("Call ended", call);
    },err => {
        console.log("error while ending call", err);
    }
)
```

Please check the same and do let us know if you face any issues.
