### ISSUE TITLE
Type

### ISSUE THREAD

**Issue by rhutchison** [cometchat-pro/javascript-chat-sdk#69]
https://github.com/cometchat-pro/javascript-chat-sdk/blob/master/CometChat.d.ts#L729

Is this library OSS so we can contribute?

**Comment by adityagokula2210** [comment]
Hello @rhutchison 

Please feel free to submit pull requests and we will be happy to incorporate your suggestions :blush:

**Comment by rhutchison** [comment]
@adityagokula2210 glad to see it was resolve.  https://github.com/cometchat-pro/javascript-chat-sdk/commit/0b106f3aa5aadc42015f3eb840a5b096234ecd4b#diff-4ff6300e45530977c28b87d88fce2648R747.

Honestly, I would love to open a PR, but this project is not setup for external contributions.  If you are willing to put the un-minified/uglified source, I will start opening other PRs.

cc: @mayur-bhandari

**Comment by majirosstefan** [comment]
In some non-traditional environments it's really hard to debug what's going on if the code is minified.
E.g. when implementing video calls with React Native Web (in web app created from React Native source code).
