### ISSUE TITLE
Issue with cometchat SDK for non-react native projects

### ISSUE THREAD

**Issue by kshitizshakya-cc** [cometchat-pro/javascript-chat-sdk#7]
For non-react-native projects

node_modules/@cometchat-pro/chat' gives error while building project, 

react-native module not found

**Comment by njbasan** [comment]
![image](https://user-images.githubusercontent.com/3722058/57764842-d7902c00-7736-11e9-82a4-5cdb83f7e1fd.png)

**Comment by njbasan** [comment]
I'm still getting the same error when compiling after updating to 1.4.3

**Comment by kshitizshakya-cc** [comment]
Hello @zxcnasab ,

We like to inform you that reported issue is warning received when you are not using react-native library in your javascript project. We can assure you that this issue will not affect your app development process. Also, We will remove this warning in the upcoming SDK release.

**Comment by ajaygajra** [comment]
@kshitizshakya  can you please confirm with new release `v1.8.1`

**Comment by njbasan** [comment]
nice! the warning is gone now. thank you.
