### ISSUE TITLE
Documentation incorrect.

### ISSUE THREAD

**Issue by GavinThomas1192** [cometchat-pro/javascript-chat-sdk#73]
Hello, 
Your docs for https://prodocs.cometchat.com/docs/js-users-retrieve-users#retrieve-list-of-users, step 3, setStatus. 

Incorrectly uses setUserStatus in the example causing a crash.

Please update the example to show setStatus vs setUserStatus.

**Comment by mayur-bhandari** [comment]
Hello @GavinThomas1192 ,

Thanks for pointing this out. We have made the changes in our documentation.

**Comment by puredazzle** [comment]
Hi, I don't think this is updated, https://prodocs.cometchat.com/v2.1-beta/docs/js-users-retrieve-users#retrieve-list-of-users
