### ISSUE TITLE
Error: Failed to execute 'send' on 'websocket' : Still in CONNECTING state.

### ISSUE THREAD

**Issue by meesrutten** [cometchat-pro/javascript-chat-sdk#74]
People are still receiving this error message, but the issue is closed:

https://github.com/cometchat-pro/javascript-chat-sdk/issues/53

**Comment by mayur-bhandari** [comment]
Closing this issue since it is a duplicate. I have reopened [this](https://github.com/cometchat-pro/javascript-chat-sdk/issues/53) issue. Please post your queries there.
