### ISSUE TITLE
Deleting a conversation

### ISSUE THREAD

**Issue by meesrutten** [cometchat-pro/javascript-chat-sdk#76]
How can a conversation be removed?
In the docs it seems that it is only possible to remove messages.

**Comment by mayur-bhandari** [comment]
Hello @meesrutten ,

Currently, delete conversation is not present in the SDK. To delete a conversation you can use our API. I am sharing the link to our API documentation below.

https://prodocs.cometchat.com/reference#delete-conversation-for-a-user
