### ISSUE TITLE
Issue with SDK 1.3.0 whenever message is send  

### ISSUE THREAD

**Issue by kshitizshakya-cc** [cometchat-pro/javascript-chat-sdk#8]

**Comment by njbasan** [comment]
![image](https://user-images.githubusercontent.com/3722058/57710680-f8f20900-769f-11e9-8489-6ca6c2733c89.png)

**Comment by mayur-bhandari** [comment]
Please update to the latest version of cometchat pro sdk and if the issue persist please let us know.
