### ISSUE TITLE
AUTH_ERR_AUTH_TOKEN_NOT_FOUND

### ISSUE THREAD

**Issue by fpvrc** [cometchat-pro/javascript-chat-sdk#80]
### Describe the problem

> Provide a clear and concise description of the issue

Im trying to join a group right after I login, however, I get the same error every time even after succesful logins.

### What was the expected behavior?

> Tell us about the behavior you expected to see
Im expecting to be able to join a group If I successfully create a user and login...
CometChat.login(newUser.uid, authKey).then(
                        authUser => {
                          var GUID = `${user.#######}`;
                          var password = "";
                          var groupType = CometChat.GROUP_TYPE.PUBLIC;
                          CometChat.joinGroup(GUID, groupType, password).then( () =>....

### Reproduction

> Detail the steps taken to reproduce this error, and whether this issue can be reproduced consistently or if it is intermittent.
> **Note**: If clear, reproducable steps or the smallest sample app demonstrating misbehavior cannot be provided, we may not be able to follow up on this bug report.

- Step 1..
- Step 2..
- ...

> Where applicable, please include:
>
> - The smallest possible sample app that reproduces the undesirable behavior
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - Screenshots

### Environment

> Please provide the following:

- **Version used:**
- **Other modules/plugins/libraries that might be involved:**

**Comment by mayur-bhandari** [comment]
Hello @fpvrc ,

Can you please let us know the version of the SDK you are using. Also can you please share the exact code snippet and steps to reproduce the issue.

**Comment by proveshapyne** [comment]
Hello @fpvrc,

We are closing this ticket due to inactivity. 
For further technical assistance, feel free to create another ticket or reach out to us at help@cometchat.com.

Regards,
Provesha
