### ISSUE TITLE
Shutdown Client

### ISSUE THREAD

**Issue by mattensor** [cometchat-pro/javascript-chat-sdk#84]
### Describe the problem

Hey 👋 I have a use case to shutdown the CometChat client, essentially an undo of the init function. Is there an simple way to do this?

Thanks

**Comment by mayur-bhandari** [comment]
Hi @Mattensor,

Sorry for the delayed response. You can use the CometChat.logout() method to shut down the client. You can read more about this method [here](https://www.cometchat.com/docs/javascript-chat-sdk/authentication#logout).

Hope this helps.
