### ISSUE TITLE
undocumented and untyped - `_composedAt` `_id`

### ISSUE THREAD

**Issue by reslear** [cometchat-pro/javascript-chat-sdk#85]
when create the new message, before sending, ui use this solution, but the not declared and not documented:

https://github.com/cometchat-pro/cometchat-pro-vue-ui-kit/blob/17f54e8900271d0fe8bf8c931804bd0015a33017/CometChatWorkspace/src/components/Messages/CometChatMessageComposer/CometChatMessageComposer.vue#L854-L855

**Comment by prakash-cometchat** [comment]
Hi reslear, 
These two keys, **_composedAt** & **_id** we use internally in our UI kits for optimistic UI. It's not needed in SDK method hence we haven't documented it.

Thanks
