### ISSUE TITLE
Issue in integration in Angular SSR application 

### ISSUE THREAD

**Issue by swadeshRanjeet** [cometchat-pro/javascript-chat-sdk#86]
I found an issue when I am using this plug-in in my angular SSR application... How can I integrate in my angular SSR application...any solution????????????

**Comment by mayur-bhandari** [comment]
Hi @swadeshRanjeet,

Can you please let us know what issue you are facing? Also, just wanted to let you know that the SDK may not work in a complete SSR setup. You would have to load the SDK on client side with SSR disabled and rest of your application can be SSR compatible.

**Comment by swadeshRanjeet** [comment]
But my complete project run on angular SSR , then how I load comit chat SDK , my error was when I am building application the project does not run.

**Comment by swadeshRanjeet** [comment]
> Hi @swadeshRanjeet,
> 
> Can you please let us know what issue you are facing? Also, just wanted to let you know that the SDK may not work in a complete SSR setup. You would have to load the SDK on client side with SSR disabled and rest of your application can be SSR compatible. 

I want to implement comit chat in my angular SSR application...show me some dummy so that I can implement it
