### ISSUE TITLE
Getting issue upon initialization and login

### ISSUE THREAD

**Issue by njbasan** [cometchat-pro/javascript-chat-sdk#9]
![image](https://user-images.githubusercontent.com/3722058/57868432-8e72d180-7835-11e9-9969-29818750390c.png)

this only happens on chrome but on firefox, I'm getting this error instead
![image](https://user-images.githubusercontent.com/3722058/57868502-b06c5400-7835-11e9-9471-3f7e332146c5.png)

seems like chrome is throwing a detailed error

**Comment by adityagokula2210** [comment]
@zxcnasab 
Just to confirm, Can you please make sure, if the login method is called only once the CometChat.init() method is successfully executed. I mean the login method should only be called after the init() method is executed completely. 

Thanks.
